version: '3'

services:
    web:
        image:          pietrovich/alpine-nginx-php7.1:${CONTAINER_VERSION}
        container_name: apps
        build: ./
        ports:
            - "80:80"
        volumes:
            - ./var/www:/var/www
